### ISSUE TITLE
Client entity improvements

### ISSUE THREAD

**Issue by weitzhandler** [TrackableEntities/TrackableEntities.Core#11]
Would be nice to expand the client `EntityBase` to implement validation logic according to data gathered from the client, injected by the model.

We might want to use existing interface such as [`IDataErrorInfo`](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.idataerrorinfo?view=netstandard-2.0)(.NET Standard 2.0).

EntityBase will expose an atomic validation method, but in addition will expose a `Validate(IValidationInfo validationInfo)`, to be used and orchestrated by the `ChangeTrackingCollection`, and again, defaulting to the defaults, or if injected by IoC, the registered setup.

In addition, see [this](https://github.com/TrackableEntities/TrackableEntities.Core/issues/10#issuecomment-348815860).
We have to thrive making the `EntityBase` in the client as flexible as possible.

For any action, we want to expose a `OnActionDone(params)` virtual (or partial if generated) method.

**Comment by tonysneed** [comment]
Are you using an MVVM framework? Many provide this. (I have one called Simple MVVM Toolkit, but I also like MVVM Cross.)

**Comment by weitzhandler** [comment]
I use Prism, but it doesn't really matter. To avoid DRY, and especially once we already have the basic validation info intercepted from the server, we want to make use of it in our client-side model.

Therefore, `EntityBase` should also implement:

- `INotifyPropertyChanged`
- `INotifyPropertyChanging`
- `IRevertibleChangeTracking`
- `IDataErrorInfo`/`INotifyDataErrorInfo`
- `IEditableObject`

All of which are part of .NET Standard 2.0.
These interfaces will not only give a lot of flexibility and extensibility option to the developer, but will give ourselves (as TE), easier way to efficiently track and manipulate the object graph, and will also make implementation of caching a much simpler option.

**Comment by tonysneed** [comment]
I think it comes down to the Single Responsibility Principal. There’s no reason to make TE aware of validation, as it’s a separate concern. So the base class with validation code can extend the TE base class, for example.  That way you keep your code DRY, but cleanly factored.

**Comment by weitzhandler** [comment]
Ok let's leave the validation alone for now

**Comment by tonysneed** [comment]
Thanks for understanding.

**Comment by weitzhandler** [comment]
> Thanks for understanding.

I don't agree it should remain outside of scope :(
I only agree it shouldn't be prioritized and that it's not important for now.

That being said, and whether we end up implementing validation or not, we sure want to leave the edges open for extension, so basing `EntityBase` on the [mentioned interfaces](https://github.com/TrackableEntities/TrackableEntities.Core/issues/11#issuecomment-349167833) (excluding validation), and providing all methods virtual is really important right from the start.

**Comment by tonysneed** [comment]
I like the idea of using interfaces that are well-factored.  I just think that validation needs to be a separate package.  But I agree on using `INotifyPropertyChanged`, `INotifyPropertyChanging`, `IChangeTracking` and `IRevertibleChangeTracking`.

**Comment by weitzhandler** [comment]
I actually think that validation should be included, because we already have the validation info.
But, we can have the validation in an external package that is based on the original one, and we'll be able to use `ValidatableEntityBase` instead of just `EntityBase`, and have an enhanced `ChangeTrackingCollection` that is extensible and will allow plugging in validation, caching etc. etc., as external modules.

**Comment by weitzhandler** [comment]
OK I made a separate issue about those interfaces: #14.
