### ISSUE TITLE
Reuse existing BCL infrastracture

### ISSUE THREAD

**Issue by weitzhandler** [TrackableEntities/TrackableEntities.Core#14]
Hi,

We've spoke about it, so I'm dedicating an issue for it.
I'm proposing to have the client entities implement some existing .NET interfaces that will make the concept of entity tracking and collection tracking much easier and more conventional.

Another aspect we want to consider, since the `BaseEntity` is to be used as the base-class for all client side entities, the more functionality we add (leaving all implemented methods virtual, of course), the better, especially those with direct relationship to TrackableEntities, such as syncing, caching, reverting all changes, validation metadata downloaded from server, etc. etc. Some of which are to be left as external extension points.

The interfaces to be considered (all in .NET Standard 2.0):

- [`INotifyPropertyChanged`](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.inotifypropertychanged?view=netstandard-2.0)
- [`INotifyPropertyChanging`](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.inotifypropertychanging?view=netstandard-2.0)
- [`IChangeTracking`](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.ichangetracking?view=netstandard-2.0)
- [`IRevertibleChangeTracking`](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.irevertiblechangetracking?view=netstandard-2.0)
- [`IEditableObject`](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.ieditableobject?view=netstandard-2.0)
- [`IDataErrorInfo`](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.idataerrorinfo?view=netstandard-2.0)
- [`INotifyDataErrorInfo`](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.inotifydataerrorinfo?view=netstandard-2.0)

For the various collections, this interface may be consider:

- [`INotifyCollectionChanged`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.inotifycollectionchanged?view=netstandard-2.0)
- [`INotifyPropertyChanged`](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.inotifypropertychanged?view=netstandard-2.0) - notify about properties in the CTC, such has `HasChanges`, `ChangeCount`, `IDictionary<TEntity, TrackingState> ChangedEntities` etc. etc.
- [`INotifyPropertyChanging`](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.inotifypropertychanging?view=netstandard-2.0)
- [`IBindingList`](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.ibindinglist?view=netstandard-2.0)
- [`ICancelAddNew`](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.icanceladdnew?view=netstandard-2.0)

The class `BindingList<T>` is what we want the `ChangeTrackingCollection` to implement. It will give us a solid ground to base all the tracking functionality on, we would probably want to steal [some code](https://source.dot.net/#System.ComponentModel.TypeConverter/System/ComponentModel/BindingList.cs,55afabf0a74c12cc) from it.

**Comment by tonysneed** [comment]
Deferring this issue for now, since I don't have plans to port the client packages to .NET Core.
