### ISSUE TITLE
Modified properties can avoid duplicates.

### ISSUE THREAD

**Issue by noufionline** [TrackableEntities/TrackableEntities.Core#17]
![trackable entities error](https://user-images.githubusercontent.com/13216154/37694936-ad76967c-2ce4-11e8-8445-f791e44e4885.jpg)

**Comment by tonysneed** [comment]
Sorry I missed this one. `ITrackable` defines `ModifiedProperties` as `ICollection<string>`, so you can implement it using a `HashSet<string>`, which will avoid creating duplicates.  For example:

```csharp
customer.ModifiedProperties = new HashSet<string>();
customer.ModifiedProperties.Add(nameof(Customer.ContactName));
customer.ModifiedProperties.Add(nameof(Customer.ContactName));
customer.ModifiedProperties.Add(nameof(Customer.ContactName));
Debug.Print($"ModifiedProperties.Count: {customer.ModifiedProperties.Count}");
// Prints: ModifiedProperties.Count: 1
```

Feel free to re-open this issue if you need any further clarification.
