### ISSUE TITLE
.NET Core/EF 3.0 - Owned Entity - Error on insert

### ISSUE THREAD

**Issue by IvanFarkas** [TrackableEntities/TrackableEntities.Core#27]
I am unable to insert when there is one or more owned entities (no nested entities).
It's working with DBContext.
**Using:**
- Using [URF.NET](https://github.com/urfnet/URF.NET)
- .NET Core SDK 3.0.100-preview3-010431
- Microsoft.EntityFrameworkCore 3.0.0-preview3.19153.1

**Exception:**
`The entity of type 'Entity' is sharing the table 'Entity' with entities of type 'Entity.OwnedEntity#OwnedEntity', but there is no entity of this type with the same key value '{Id: -2147482647}' that has been marked as 'Added'.
`

It's a known issue.
See: **[EF Core 2 Owned Entities and Temporary Work-Arounds](https://msdn.microsoft.com/en-us/magazine/mt846463.aspx)**
Would be nice to have a fix or at least a roadmap to fix this in the trackable entities.

**Comment by tonysneed** [comment]
Would this be resolved by upgrading TrackableEntities.Core to EF Core 3.0?

**Comment by tonysneed** [comment]
Please re-open if this is still an issue.
