### ISSUE TITLE
DbContextExtensionsInternal.TraverseGraph - critical error

### ISSUE THREAD

**Issue by fomtamaskiss** [TrackableEntities/TrackableEntities.Core#29]
Hello,

In DbContextExtensionsInternal.TraverseGraph/Async when you iterate through the entity relation graph you store the visited object's hashcode in HashSet\<int\>. It can cause "randomly" skipping items, because GetHashCode() is not unique! This is a very sneaking error, because it sometimes fails and you will never reproduce. Simply use HashSet\<object\> and put the EntityEntry object into it.

**Comment by tonysneed** [comment]
Good catch! I'll have a look at this. In the meantime, I'm happy to accept pull requests! 😄
