### ISSUE TITLE
GetRelationshipType() extension method is broken in EF Core 5

### ISSUE THREAD

**Issue by noufionline** [TrackableEntities/TrackableEntities.Core#36]
https://github.com/TrackableEntities/TrackableEntities.Core/blob/fce91ab489e86a0102384a9fc887ddcd87e6b2ec/TrackableEntities.EF.Core/DbContextExtensions.cs#L39

As InboundNavigation property has changed from INavigation to INavigationBase GetRelationshipType() extension method in NavigationExtensions class no longer working.

```csharp
  public static RelationshipType? GetRelationshipType(this INavigation nav)
```

![Screenshot 2020-11-12 083329](https://user-images.githubusercontent.com/13216154/98896202-db367780-24c1-11eb-8402-4f9eb5b5e60e.png)

**Comment by tonysneed** [comment]
Thanks. Would you care to submit a PR to fix this?

**Comment by brenwebber** [comment]
https://github.com/TrackableEntities/TrackableEntities.Core/pull/37
