### ISSUE TITLE
Updating for m2m skip navigations

### ISSUE THREAD

**Issue by rkone** [TrackableEntities/TrackableEntities.Core#44]
I've been looking at updating this to support the skip navigation feature added in EF Core 5.  However I've been struggling a bit due to my knowledge of EF core being so woefully inadequate. 
Here's what I've done so far:
NavigationExtensions is updated to detect the m2m skip navigation:
```
 public static RelationshipType? GetRelationshipType(this INavigationBase navigation)
        {
            if (navigation is not INavigation nav)
            {
                if (typeof(IEnumerable<ITrackable>).IsAssignableFrom(navigation.ClrType)) return RelationshipType.ManyToMany;
                return null;
            }
            if (nav.ForeignKey.IsUnique)
                return RelationshipType.OneToOne;
            return nav.IsOnDependent ? RelationshipType.OneToMany : RelationshipType.ManyToOne;
        }
```
ApplyChanges in DBContextExtensions uses the relationship to allow handling of modifying:
```
switch (relationship)
{
...
   case RelationshipType.ManyToMany:
      // If trackable is set modified, set entity state to unchanged before attaching.
      // this tells the skip navigation to be unchanged.
      if (trackable.TrackingState == TrackingState.Modified)
      {
          SetEntityState(node.Entry, TrackingState.Unchanged.ToEntityState(), trackable);                                
      }

      // If trackable is set deleted, mark as deleted to delete skip navigation,
      // then return return entity state to unchanged since it may be related to other entities.                            
      if (trackable.TrackingState == TrackingState.Deleted)
      {
          //not working.
          SetEntityState(node.Entry, TrackingState.Unchanged.ToEntityState(), trackable);
          SetEntityState(node.Entry, TrackingState.Deleted.ToEntityState(), trackable);
          SetEntityState(node.Entry, TrackingState.Unchanged.ToEntityState(), trackable);
          return;
      }
      break;
```
ajvickers from the EF Core team was able to assist with the method to mark the skip navigation as unchanged (Join the attached entity as unchanged, then change it to modified.
Unfortunately I'm not able to come up with a way to only mark the skip navigation as deleted but leave parent and child entities as unchanged.  Does anyone have any insight on this?

**Comment by Jaben** [comment]
@rkone did you ever circle back to this problem or figure out a solution?

**Comment by rkone** [comment]
Nope, unfortunately it hasn't been a high enough priority for me yet. But if you're thinking about looking into it, you might want to check out my fork, I have everything moved to .net 8 - including Tony's unit tests.

**Comment by Jaben** [comment]
> Nope, unfortunately it hasn't been a high enough priority for me yet. But if you're thinking about looking into it, you might want to check out my fork, I have everything moved to .net 8 - including Tony's unit tests.

Are you talking about that branch that has *checks notes* 14,562 additions and 3,742 deletions? Not a simple PR.

**Comment by rkone** [comment]
lol, sorry.  Yes the pr ship sailed years ago

**Comment by Jaben** [comment]
> lol, sorry. Yes the pr ship sailed years ago

I'm going to close this issue for now as it's out of scope.
